//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebCAQ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBcolegioEntities : DbContext
    {
        public DBcolegioEntities()
            : base("name=DBcolegioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<cronograma> cronograma { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<galeria> galeria { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<materia> materia { get; set; }
        public virtual DbSet<nivel> nivel { get; set; }
        public virtual DbSet<personal> personal { get; set; }
    }
}
