//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebCAQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int idEvento { get; set; }
        public string nombreEvento { get; set; }
        public string descripcion { get; set; }
        public string fecha { get; set; }
        public string tipoEvento { get; set; }
        public int cronograma_idCronograma { get; set; }
    
        public virtual cronograma cronograma { get; set; }
    }
}
