//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebCAQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public int idMateria { get; set; }
        public string nombreMateria { get; set; }
        public string horario_dia { get; set; }
        public string profesor { get; set; }
        public string horario_grupo_idGrupo { get; set; }
        public int horario_grupo_nivel_idNivel { get; set; }
    
        public virtual horario horario { get; set; }
    }
}
